# Generated by Django 2.2.11 on 2020-07-11 03:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calidadmot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razon_visita', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('Nombre', models.CharField(max_length=100)),
                ('Visitado', models.CharField(max_length=100)),
                ('Fecha_visita', models.DateField(default=datetime.date.today)),
                ('Motivo_visita', models.CharField(max_length=200)),
                ('Numero_de_visita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now)),
                ('Calidad_de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitas.Calidadmot')),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetos.Departamentos')),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitas.Empresas')),
            ],
        ),
    ]
